name: Backport merged PR commit to foxy-fortress branch and create a PR

on:
  workflow_dispatch:
  push:
    branches:
      - master
     
jobs:
  release_pull_request:
    runs-on: ubuntu-20.04
    name: release_pull_request
    steps:
    - name: checkout deepx_ci
      uses: actions/checkout@v3
      with:
        repository: DeepX-inc/deepx_ci
        path: deepx_ci
        ref: "v0.6.0"
        ssh-key: ${{ secrets.DETRABOT_SECRET }}
    - name: Create PR to foxy-fortress
      uses: ./deepx_ci/actions/cherry-pick@feature/cherry_pick
      with:
        pr_branch: 'foxy-fortress'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_KEY: ${{ secrets.DETRABOT_GPG_KEY }}
        GPG_PASSPHRASE: ${{ secrets.DETRABOT_GPG_PASSPHRASE }}
        DRY_RUN: false
